server:
  port: ${PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/seed
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  mail:
    host: smtp.naver.com
    port: 465
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            trust: smtp.naver.com
            enable: true
security:
  patterns:
    ignoring:
      GET:
        - /users/signup
      POST:
        - /api/users/signup
        - /api/users/signin
        - /api/users/email-check
      PATCH:
        - /api/users/email-confirm
      PUT: [ ]
      DELETE: [ ]
    permit-all:
      GET: [ ]
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
      OPTIONS: [ ]
  jwt:
    issuer: payhere
    accessToken:
      header: at
      expiry-seconds: 21600
    refreshToken:
      header: rt
      expiry-seconds: 28800