version: '3.8'

networks:
  default:
    name: payhere

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  mysql5.7:
    image: mysql:5.7
    container_name: mysql5.7
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=ledger
      - MYSQL_PASSWORD=password
    platform: linux/amd64
    restart: always

  mysql5.7-phpmyadmin:
    depends_on:
      - mysql5.7
    image: phpmyadmin/phpmyadmin
    container_name: mysql5.7-phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password 
    platform: linux/amd64
    restart: always